### ISSUE TITLE
Function: Delete Movie Club

### ISSUE THREAD

**Issue by m-lair** [m-lair/MovieClub#15]
Develop a Cloud Function to delete a Movie Club and all its related data.

 

- [ ] Check user role for delete permission.
- [ ]  Delete associated movies and suggestions within the club.
- [ ]  Ensure safe database removal of all related data.
- [ ]  Add unit and integration tests.

**Comment by Codball** [comment]
@m-lair I've been thinking about this and the other deletes, do we want to hard delete or soft delete these records? I imagine having analytics on these records might still be useful even though the user no longer wants to use it.

**Comment by m-lair** [comment]
> @m-lair I've been thinking about this and the other deletes, do we want to hard delete or soft delete these records? I imagine having analytics on these records might still be useful even though the user no longer wants to use it.

yeah I agree. a soft delete is probably best. retain for maybe 90 days to start with?

**Comment by Codball** [comment]
> retain for maybe 90 days to start with?
In this case, I'm not sure how we want to approach hard deleting old records but that sounds like a separate card. I also think there's an argument for never deleting them but we would want to identify the cost of retaining everything indefinitely and can approach it at a later date when we determine what sort of analytics we want to track.

**Comment by mney33** [comment]
I noted on our trello board the need to discuss this further. Both the minimum viable product requirements and the V2 requirements will define these.
