### ISSUE TITLE
Functions: Leaving a Club

### ISSUE THREAD

**Issue by m-lair** [m-lair/MovieClub#16]
Create a Cloud Function to handle a user leaving a Movie Club, including cleanup of associated data.

- [ ] Validate user membership in the club.
- [x]  Remove the user from the club's member list.
- [x]  Clean up user-related data (e.g., suggestions).
- [x]  Add unit and integration tests.

**Comment by Codball** [comment]
@m-lair I think validating the membership here might not be necessary since these delete operations results in there being no records either way and we can avoid the read. Let me know if that logic is sound.

**Comment by m-lair** [comment]
Yeah that sounds good to me!
