### ISSUE TITLE
Swift: Limit User to One Suggestion

### ISSUE THREAD

**Issue by m-lair** [m-lair/MovieClub#51]
Currently, the suggestion creation logic uses the user's uid as the document ID. This causes a problem where, if a user submits another suggestion, it overwrites their previous suggestion, updating the createdAt field. This might not be the intended behavior if we want to allow users to track their previous submissions.

- [ ] edit create suggestion view to check if the user already has an existing suggestion for that club
- [ ] tests
- [ ] ui changes

**Comment by m-lair** [comment]
i dont think we need to track previous tbh. all existing suggestions can really be the only thing i can think of and thats easy enough to fetch with what we have

**Comment by Codball** [comment]
Does that mean we can close this issue?

**Comment by m-lair** [comment]
yeah sorry this was more just so I dont forget. easiest to just create a new issue from ur comment on the other branch!
